/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Clear Log": "清理日志",
    "Dig Site": "挖掘地点",
    "Hire a Student": "雇佣 1 名学生",
    "Hire some students to dust off relics for you. They work for relics.": "雇一些学生为你清理文物。 他们为文物工作。",
    "Look for relics": "发掘文物",
    "Relics": "文物",
    "The new dig site lays before me, I wonder what treasures lay yet unearthed?": "新的挖掘地点在我面前，我想知道还有什么宝藏出土？",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "The wind blows across the dusty plain": "风吹过尘土飞扬的平原",
    "You dust off some potsherds.": "你清理出一些陶片。",
    "Game Saved": "游戏已保存",
    "Clear Save": "删除进度",
    "Patch Notes": "更新日志",
    "Relics - A game by bearhanded.": "文物发掘放置 - 一个不折不扣的游戏。",
    "The game saves automatically every 30s.": "游戏每 30 秒自动保存一次。",
    "Toggle Dark Mode": "切换深色模式",
    "Gather Relics": "收集文物",
    "Job Assignments": "工作分配",
    "Students": "学生",
    "I know enough about this to teach others to do the work, albeit at a reduced efficiency.": "我对此有足够的了解，可以教别人做这项工作，尽管效率会降低。",
    "A stranger shuffles up and hands something to you: +100 Relics!": "一个陌生人拖着脚步，递给你一些东西：+100 文物！",
    "Knowledge": "知识",
    "Map the Ruins": "绘制废墟地图",
    "Peruse your collection, perhaps you can find something useful.": "细读你的收藏，也许你能找到一些有用的东西。",
    "Research": "研究",
    "Research Lab": "研究实验室",
    "Studious Students": "勤奋好学的学生",
    "Study Relics": "研究文物",
    "These relics seem to be found near a few particular features.": "这些文物似乎在一些特定特征附近被发现。",
    "With your new found stash of relics, you retreat to your personal laboratory!": "带着你新发现的遗物，你撤退到你的个人实验室！",
    "A shout in the dark. You are short one student.": "黑暗中的一声呐喊。 你缺一个学生。",
    "Blood": "血",
    "Procure Funding": "获得资金",
    "Produces .1 knowledge per 10 relics.": "每 10 个文物产生 0.1 知识。",
    "Student Studying Relics": "学生研究文物",
    "With your student's help, you know enough now to fund this endeavor. A little embellishment never hurt...": "在您的学生的帮助下，您现在知道的足够多，可以资助这项工作。 一点点的点缀永远不会伤害...",
    "A patron finds your work interesting, and provides a slow but steady drip of funding.": "赞助人发现您的工作很有趣，并提供缓慢但稳定的资金。",
    "Better Shovels": "更好的铲子",
    "Money": "资金",
    "Buy the team their very first shovel. It's better than none.": "为团队购买他们的第一把铲子。 总比没有好。",
    "Inscribe a ward": "注册保护区",
    "More funding": "更多资金",
    "Student base gathering rate +0.5 relics": "学生基础采集率 +0.5 文物",
    "The excavated ruins are carved with a repeating pattern, and no one has disappeared in there yet.": "发掘出来的文物上刻着重复的图案，至今没有一个人在里面消失过。",
    "You form a committee of students to think very hard about how to make more money.": "你组建了一个学生委员会，认真思考如何赚更多的钱。",
    "Buildings": "建筑",
    "It turns out we don't need to keep our relics in a pile under a tarp.": "事实证明，我们不需要将我们的文物堆放在防水布下。",
    "Search Algorithms": "搜索算法",
    "Storage Shed": "储物棚",
    "Teach the students how to search more efficiently. It works for you but it might just be confirmation bias.": "教学生如何更有效地搜索。 它对你有用，但它可能只是确认偏差。",
    "Following instructions on the ruins, you assemble a ward. That should protect this place.": "按照废墟上的指示，你圈出了一个保护区。 那应该能保护这个地方。",
    "Ritual Chamber": "仪式室",
    "Set aside a location and prepare it for incantations. You must find a way to protect your work.": "留出一个位置并为咒语做好准备。 您必须找到一种方法来保护您的工作。",
    "Unlocks the Ritual Chamber.": "解锁仪式室。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Increases manual base relic search rate by ": "将手动基础文物搜索率提高 ",
    "Knowledge: ": "知识: ",
    "Relics: ": "文物: ",
    "Blood: ": "血: ",
    "Money: ": "资金: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " Knowledge cap": " 知识上限",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Shovel$/, '$1 铲子'],
    [/^([\d\.,]+) relic storage.$/, '$1 文物库存空间'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);